# Apply the 'Core' label if any .csproj file or any file in the 'core/' directory is changed.
Core:
  - changed-files:
    - any-glob-to-any-file: 
      - '**/*.csproj'
      - 'core/**/*'
      - '**/.editorconfig'

# Apply the 'Documentation' label for any change to a Markdown file.
Documentation:
  - changed-files:
    - any-glob-to-any-file: '**/*.md'
